<div class="add-task-form">

    <form class="form-horizontal" role="form" name="addTaskExtForm">
        <div class="form-group" ng-class="{'has-error': addTaskExtForm.hours_max.$dirty && addTaskExtForm.hours_max.$invalid}">
            <label class="col-sm-3 control-label" for="hours_max">Est. time</label>
            <div class="col-sm-4">
                <input type="text" name="hours_max" class="form-control" ng-model="newTask.hoursMax" value="" required>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label" for="details" >Details</label>
            <div class="col-sm-8">
                <textarea name="details" class="form-control" rows="5" ng-model="newTask.details"></textarea>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-10">
                <input type="submit" name="add"
                       class="btn btn-primary"
                       ng-click="addTask()"
                       value="Add" />
            </div>
        </div>
    </form>

</div>