<?php

$this->headScript()->appendFile($this->basePath('js/agister.js'));
$this->headLink()->appendStylesheet($this->basePath('css/agister.css'));

?>
<div class="row">

    <div ng-class="{'col-md-12': !taskDetailsVisible, 'col-md-8': taskDetailsVisible}">
        <table class="timeline-table">
            <tr>
                <td class="title">
                    Task
                </td>
                <td>
                    <div class="legend-wrapper">
                        <div class="date-marker"
                             style="left: {{ date.seconds * date.scale * 0.95 }}%"
                             ng-repeat="date in dateMarkers">
                            {{ date.date }}
                        </div>
                    </div>
                </td>
            </tr>
            <tr ng-repeat="task in tasks">
                <td class="title" ng-click="loadTaskDetails(task.id)">
                    {{ task.title }}
                </td>
                <td class="timeline">
                    <div class="task-container">
                        <div ng-class="{task: true, completed: task.completed}"
                             ng-click="loadTaskDetails(task.id)"
                             style="margin-left: {{ task.scaledStart }}%; width: {{ task.scaledWidth }}%">
                        </div>
                    </div>
                </td>
            </tr>
            <tr ng-hide="tasks.length">
                <td colspan="2">
                    <em>Task list is empty. Add new tasks using form above.</em>
                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-4" ng-show="taskDetailsVisible">
        <div class="task-details">
            <button type="button" class="close" ng-click="taskDetailsVisible = false">&times;</button>
            <header>
                <h4>
                    {{ currentTask.title }}
                    <span ng-show="currentTask.completed">(completed)</span>
                </h4>
            </header>

            <dl class="info">
                <dt>Estimate</dt>
                <dd>{{ currentTaskViewModel.estimate }}</dd>
                <dt>Start</dt>
                <dd>{{ currentTaskViewModel.startsAt }}</dd>
                <dt>Finish</dt>
                <dd>{{ currentTaskViewModel.finishesAt }}</dd>
                <dt>Details</dt>
                <dd ng-show="currentTask.details">{{ currentTask.details }}</dd>
                <dd ng-show="!currentTask.details"><em>no details are available</em></dd>
            </dl>

            <button type="button" class="btn btn-success"
                    ng-click="completeTask(currentTask.id)"
                    ng-show="!currentTask.completed"
                >
                <span class="glyphicon glyphicon-check"></span>
                Mark as completed
            </button>
            <button type="button" class="btn btn-danger" ng-click="deleteTask(currentTask.id)">
                <span class="glyphicon glyphicon-remove"></span>
                Remove
            </button>
        </div>
    </div>
</div>
