<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("AGIster")->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php

        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>

        <?php
        echo $this->headLink(array(
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico')
            )
            ->prependStylesheet($this->basePath( 'vendor/bootstrap/dist/css/bootstrap.min.css'))
        ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath('vendor/bootstrap/dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('vendor/angular/angular.js'))
            ->prependFile($this->basePath('vendor/jquery/jquery.min.js'))
        ; ?>

    </head>
    <body  data-base-path="<?php echo $this->basePath() ?>">
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> Mateusz Tymek. All rights reserved.</p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
