<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("AGIster")->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php

        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>

        <?php
        echo $this->headLink(array(
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico')
            )
            ->prependStylesheet($this->basePath( 'vendor/bootstrap/dist/css/bootstrap.min.css'))
        ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath('vendor/bootstrap/dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('vendor/angular/angular.js'))
            ->prependFile($this->basePath('vendor/jquery/jquery.min.js'))
        ; ?>

    </head>
    <body  data-base-path="<?php echo $this->basePath() ?>" ng-app="agister" ng-controller="AgisterDashboardController">

        <nav class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="agister-container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->basePath('/') ?>">AGIster</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="#">Reports</a></li>
                </ul>
                <div class="add-task-wrapper">
                    <form class="navbar-form navbar-left" action="">
                        <div class="form-group">
                            <input class="form-control"
                                   type="text"
                                   name="task-title"
                                   placeholder="Type to add new task"
                                   ng-focus="addTaskFormVisible = true"
                                   ng-model="newTask.title"
                                />
                        </div>
                    </form>
                    <div class="add-task-full" ng-show="addTaskFormVisible">
                        <?php echo $this->addTaskForm() ?>
                    </div>
                </div>
            </div>
        </nav>

        <div class="agister-container" ng-click="addTaskFormVisible = false">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> Mateusz Tymek. All rights reserved.</p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
